apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: artifact-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    # sensor controller will use this label to match with it's own version
    argo-events-sensor-version: v0.10
    needs: proxy
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  dependencies:
    - name: "artifact-gateway:example-1"
  triggers:
    - template:
        name: artifact-workflow-trigger
        group: ""
        version: v1
        kind: Pod
        source:
          url:
            path: "https://github.com/jw3/kfp-runner/pod.yaml"
            verifyCert: false
      # The container args from the workflow are overridden by the s3 notification key
      resourceParameters:
        - src:
            event: "artifact-gateway:example-1"
            path: s3.object.key
          dest: spec.templates.0.container.args.0
