apiVersion: v1
kind: Pod
metadata:
  name: kfp-runner
  # com.github.jw3/kfp-runner/default-pipeline: true
spec:
  containers:
    - name: main
      image: "jwiii/kfp-runner:latest"
      args:
        - "job_name"
