apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: kfp-sensor
  labels:
    sensors.argoproj.io/sensor-controller-instanceid: argo-events
    # sensor controller will use this label to match with it's own version
    argo-events-sensor-version: v0.10
    needs: proxy
spec:
  template:
    spec:
      containers:
        - name: "sensor"
          image: "argoproj/sensor"
          imagePullPolicy: Always
      serviceAccountName: argo-events-sa
  eventProtocol:
    type: "HTTP"
    http:
      port: "9300"
  dependencies:
    - name: "artifact-gateway:example-1"
  triggers:
    - template:
        name: artifact-workflow-trigger
        group: ""
        version: v1
        kind: Job
        source:
          inline: |
            apiVersion: batch/v1
            kind: Job
            metadata:
              generateName: kfp-runner-
            spec:
              template:
                metadata:
                  labels:
                    com.github.jw3.kfp-runner/pipeline: "true"
                spec:
                  restartPolicy: OnFailure
                  containers:
                    - name: main
                      image: jwiii/kfp-runner:latest
                      args:
                        - __s3_object_key__
      # The container args from the workflow are overridden by the s3 notification key
      resourceParameters:
        - src:
            event: "artifact-gateway:example-1"
            path: s3.object.key
          dest: spec.template.spec.containers.0.args.0
